#!/usr/bin/php
<?php

use Cli\Basic\Cli;
use Cli\Basic\Formatter;
use Cli\Basic\Flags;
use Cli\Basic\Params;
use Cli\Basic\Environment;

spl_autoload_register(function($class) {
    $class = str_replace('\\', '/', $class);
    $class = preg_replace('/^Cli\//', '', $class, 1);
    include_once "src/$class.php";
});

Cli::initialize([
    'script_file_name'            => './cli',
    'enable_list'                 => 'on',
    'enable_exceptions'           => 'on',
    'enable_errors'               => 'on',
    'enable_find_command_package' => 'on',
]);

Cli::handle('bit', function(Params $params){
    $fmt = new Formatter($params);
    return $fmt->blue();
});

Cli::handle('table', function() {
    $data = [
        ['command', 'params', 'flags'],
        ['comtomir', '[1,34,56,]', '[-f -r -d]'],
        ['comtomirner', '[1,string,56,]', '[-f -r -d]'],
    ];

    $fmt = new Formatter($data);
    return $fmt->asTable()->red();

});

Cli::handle('sayHi', function (Flags $flags, Environment $env, Params $params) { // callable
   return $env;
}, ['--send'], ['email' => 'name@mail.ru']);

Cli::run();
